### ISSUE TITLE
add the option to set repo password from a file

### ISSUE THREAD

**Issue by m-adawi** [m-adawi/swarm-cd#13]
repos.yaml file should look something like this:

```yaml
repo-name:
  url: "https://github.com/user/repo.git"
  username: user
  password_file: /path/to/password/file
```
so we can mount this password file using docker secrets
