### ISSUE TITLE
Fails to deploy stacks from different branches on the same repository

### ISSUE THREAD

**Issue by sanzoghenzo** [m-adawi/swarm-cd#33]
Hi there, 

In trying the private registry thing for #32, I added a stack on the `staging` branch of my repo (called `swarm-ops`).

This is a condensed version of my stacks.yaml:

```yaml
---
traefik:
  repo: swarm-ops
  branch: main
  compose_file: stacks/traefik/stack.yaml

my-tool:
  repo: swarm-ops
  branch: staging
  compose_file: stacks/my-tool/stack.yml
```

If I try to use this configuration, I got the following log:

```
level=INFO msg="starting SwarmCD"
level=INFO msg="updating stacks..."
level=INFO msg="updating my-tool stack"
level=ERROR msg="could not deploy stack my-tool: network \"traefik-public\" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed"
level=INFO msg="updating traefik stack"
level=ERROR msg="could not pull main branch in swarm-ops repo: non-fast-forward update"
```

The first error is to be expected, but it will be solved once the traefik stack is deployed (it declares the traefik-public network).
The second one is the problematic one.

It seems that the repository is correctly checked out (or at least it doesn't error out), but the "non-fast-forward" update suggests that the working tree is still set to the commit of the other branch (that is one commit ahead from main).
