### ISSUE TITLE
Can swarm-cd manage itself?

### ISSUE THREAD

**Issue by harshasrisri** [m-adawi/swarm-cd#54]
Hi,

So glad to have stumbled upon this project. I'm in the process of setting up my homelab using `swarm-cd`.

I couldn't find this from the issues/documentation, how can I have `swarm-cd` manage itself like it manages other repos? To elaborate, if I manage `swarm-cd` in a git repo separate from my stacks, and I add a stack to `stacks.yaml`, how can I avoid logging onto my host and updating and restarting the service?

**Comment by sanzoghenzo** [comment]
Hi @harshasrisri,

I believe you're looking for the [dynamic discovery of stacks as I requested here](https://github.com/m-adawi/swarm-cd/issues/23).

If you also want a complete self-management (for example to upgrade swarm-cd) I'm not positive, since it would result in the swarm-cd container restarting itself. 
I'm pretty new to swarm mode, so I may be wrong and it could work!
The only thing to do is to try it yourself 😉

**Comment by m-adawi** [comment]
> So glad to have stumbled upon this project. I'm in the process of setting up my homelab using swarm-cd.

I'm glad you found it useful. 

>I couldn't find this from the issues/documentation, how can I have swarm-cd manage itself like it manages other repos? To elaborate, if I manage swarm-cd in a git repo separate from my stacks, and I add a stack to stacks.yaml, how can I avoid logging onto my host and updating and restarting the service?

Yeah I think this will be useful but maybe we can already do it by defining swarm-cd as a stack in its own stacks.yaml file and define stacks.yaml, config.yaml. repos.yaml as swarm configs in its stack compose file.

**Comment by harshasrisri** [comment]
Hey @m-adawi, sorry couldn't get to try it in a while, but reading your response, I couldn't quite understand how it could be done. Do yo mean I need to run 2 instances of `swarm-cd`, where a higher level instance acts as a bootstrap just to manage the lower level instance, which then manages other stacks?

**Comment by sanzoghenzo** [comment]
Hi @harshasrisri, what @m-adawi meant is to put SwarmCD stack into its stacks.yaml config.
When you start it manually, it will then find itself in the stacks to monitor and update.

I believe it can result in weird behavior since there's no permanent state storage yet to keep track of the latest deployed version (commit hash), but I still have to try it so it's just a theory

**Comment by sanzoghenzo** [comment]
HI guys, sorry for the radio silence, work emergencies and life got in the way 😅 

I'm in the process to integrate swarm-cd in a IaC deployment made with OpenTofu (terraform fork) and I had to convert the swarm-cd compose stack to a tf module so that I can automatically deploy it after the swarm cluster is up and running.

With this new setup, I also found myself in the need to decouple the stacks.yaml (and repos.yaml) content from the swarm-cd stack definition, so that I can avoid firing up the opentofu toolchain just to add a new stack.
The proposed workaround (that I still have to test, BTW) doesn't apply to this case since I don't have the swarm-cd stack compose file anymore.

So I now totally back up this request, even more so than the wildcard search!
I'm still thinking about an elegant way to solve this, I'll get back when I got something useful

**Comment by skuzzle** [comment]
Joining the discussion as I'd also like to have swarm-cd manage itself. What I wondered is, whether we could make that work by just ensuring that the stacks are deployed in the order they are defined. Then, if you put the swarm-cd stack last, it wouldn't prematurely redeploy itself before other stacks are updated. Maybe I'm missing something but this seems like a low hanging fruit to try out?

**Comment by sanzoghenzo** [comment]
Hi @skuzzle , stacks are processed in parallel, so there's no way to ensure the execution order as of now.

> it wouldn't prematurely redeploy itself before other stacks are updated

Is that what happens to you? (Honestly, I still haven't tried this myself, and my worries were just suppositions...)

One can set swarm-cd service with "zero downtime" as I explained [here](https://github.com/m-adawi/swarm-cd/issues/130#issuecomment-3567900246), or maybe the rollback on failure configuration is all that it is needed; the swarm-cd reload should kick in only if the configuration changes, so it would only disrupt a cycle, that would be repeated as soon as swarm-cd gets back up.

**Comment by skuzzle** [comment]
Haha, I've seen that at least happen once and thought that must be the main and only issue when having swarm-cd manage itself. But I guess that you're right and the premature restart should only happen once. I'll actually try that for a while and also test the suggested zero-downtime config 🤞

**Comment by sanzoghenzo** [comment]
FYI: i finally got the time to test it myself (mostly to solve the issues I had with deploying swarm-cd via OpenTofu), and the "inception style" configuration seems to work.

This is my setup

```yaml
# stacks/swarm-cd/stack.yaml
---
version: '3.9'

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:0.3.0
    environment:
      TZ: Europe/Rome
      INFO: "1"
      SERVICES: "1"
      NETWORKS: "1"
      SECRETS: "1"
      CONFIGS: "1"
      POST: "1"
    volumes: [/var/run/docker.sock:/var/run/docker.sock:ro]
    deploy:
      placement:
        constraints: [node.role == manager]

  swarm-cd:
    image: ghcr.io/m-adawi/swarm-cd:1.11.0
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375"
      SOPS_AGE_KEY_FILE: "/run/secrets/age-key"
      GIN_MODE: "release"
    secrets:
      - age-key
      - git-token
      - source: docker-config
        target: /root/.docker/config.json
    configs:
      - source: swarm-cd-config
        target: /app/config.yaml
        mode: 0400
      - source: stacks
        target: /app/stacks.yaml
        mode: 0400

configs:
  swarm-cd-config:
    file: ./configs/config.yaml
  stacks:
    file: ./configs/stacks.yaml

secrets:
  age-key:
    file: ./secrets/age.key
  git-token:
    file: ./secrets/git-token
  docker-config:
    file: ./secrets/docker-config.json

```

```yaml
# stacks/swarm-cd/configs/config.yaml
sops_secrets_discovery: true

repos:
  swarm-ops:
    url: "https://my-repo.git"
    username: "swarmops"
    password_file: "/run/secrets/git-token"
```

```yaml
# stacks/swarm-cd/configs/stacks.yaml
swarm-cd:
  repo: swarm-ops
  branch: swarm-cd-inception
  compose_file: stacks/swarm-cd/stack.yaml
```

**NOTE**: I'm using configs and secrets in the swarm-cd compose file, and I believe this is the key for this to work.  
I have a script (well, a set of [Taskfile](https://taskfile.dev/) tasks) to decrypt the secrets and calculate the hashes, mimicking what swarm-cd does, so I can kickstart the deployment on whichever DOCKER_HOST or docker context I'm using.

I didn't try to change the image version, but it should just take a bit more time since it has to download the image, but other than that it is business as usual 😉
